[build]
  publish = "."
  command = "echo 'Nederlandse Vacature Optimizer Ready'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=()"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' *.typeform.com embed.typeform.com *.googletagmanager.com *.google-analytics.com;
      style-src 'self' 'unsafe-inline' fonts.googleapis.com *.typeform.com;
      font-src 'self' fonts.gstatic.com *.typeform.com;
      img-src 'self' data: https: *.typeform.com;
      frame-src *.typeform.com form.typeform.com https:;
      frame-ancestors 'self';
      connect-src 'self' api.anthropic.com api.pdfmonkey.io *.typeform.com *.google-analytics.com *.googletagmanager.com https:;
      object-src 'none';
      base-uri 'self';
      form-action 'self' *.typeform.com https:;
    """

# Performance Headers
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Font Optimization
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SEO redirects
[[redirects]]
  from = "/vacature-optimizer"
  to = "/"
  status = 301

[[redirects]]
  from = "/optimizer"
  to = "/"
  status = 301

# 404 handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404