[build]
  publish = "."
  command = "echo 'Nederlandse Vacature Optimizer Ready'"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Basic Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SEO redirects
[[redirects]]
  from = "/vacature-optimizer"
  to = "/"
  status = 301

[[redirects]]
  from = "/optimizer"
  to = "/"
  status = 301

# SPA fallback (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
